site_name: Zodchy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
nav:
  - Introduction: index.md
  - Base definitions:
    - Codex: 'base/codex.md'
    - Operators: 'base/operators.md'
    - Types: 'base/types.md'
  - Components:
      - DI:
          - Contracts: 'components/di/contracts.md'
          - Zorge: 'components/di/zorge.md'
      - CQRS:
          - Contracts: 'components/cqrs/contracts.md'
          - Pancho: 'components/cqrs/pancho.md'
      - Storage:
          - Contracts: 'components/storage/contracts.md'
          - Hermitage: 'components/storage/hermitage.md'
      - Notations:
          - Query:
              - Math: 'components/notations/math.md'
  - Adapters:
      - WEB:
          - FastAPI: 'adapters/web/fastapi.md'
      - RDBS:
          - SQLAlchemy: 'adapters/rdbs/sqlalchemy.md'
  - Supplements:
      - Toolsets:
          - Identity: 'supplements/toolsets/identity.md'
          - Security: 'supplements/toolsets/security.md'
          - Patterns: 'supplements/toolsets/patterns.md'
      - Storage:
          - 'SQLAlchemy Schema Builder': 'supplements/storages/alchemy_schema_builder.md'
          - 'Alembic tools': 'supplements/storages/alembic_tools.md'
      - 'Data pipelines':
          - 'Streamlord': 'supplements/pipelines/streamlord.md'
  - 'Application bootstrap': 'supplements/bootstrap.md'